### ISSUE TITLE
Bug: After refresh persistent store not return data

### ISSUE THREAD

**Issue by thisroot** [LegendApp/legend-state#417]
Same situation with `ObservablePersistMMKV`

1. Select type of storage
```js
export const persistentStorage = Platform.OS === 'web' ? ObservablePersistLocalStorage  : ObservablePersistMMKV
```

2. Set up store

```js
export const auth$ = observable<Index>({
      isAuthorized: (): boolean => !!auth$.credentials.get()?.accessToken,
      loading: false,
      credentials: undefined,
      logOut: () => {
        auth$.credentials.delete()
        router.replace("/");
      },
      authRequest: async (data: UserData): Promise<boolean> => {
       ....
          if (response.status === 200) {
            auth$.credentials.set(response.data.data);
          }
       ...
```

3. Set up persistence

```js
syncObservable(auth$, {
  persist: {
    plugin: persistentStorage,
  }
})

```

4. Check credentials

```js

if (!auth$.credentials.get()) { // true - credentials not found
    return <Redirect href="/sign-in"/>
 }
 
```

After refreshing App credentials did not restoring

**Comment by AbhieShinde** [comment]
I think this would be accessed like this

```ts
const auth = auth$.get();

if (!auth.credentials) { // false - credentials found
    return <Redirect href="/sign-in"/>
 }
```

**Comment by jmeistrich** [comment]
I think you're missing setting a `name` on the persist options: https://www.legendapp.com/open-source/state/v3/sync/persist-sync/#mmkv-rn. Multiple observables can use the same persistence plugin but need to save to a difference key inside of the persistence.

So this should fix it:

```js
syncObservable(auth$, {
  persist: {
    plugin: persistentStorage,
    name: 'auth'
  }
})
```

**Comment by abiy-120** [comment]
I have the same problem. And setting the name does not solve it

**Comment by thisroot** [comment]
@abiy-120 I dont have a time to fix it. Just return to use mobx with mobx-persistent-store. Works well!

**Comment by jmeistrich** [comment]
Can you share a full code example I can test with? It should be working, and I can't tell what's wrong from those snippets. Thanks!

**Comment by abiy-120** [comment]
It has worked now. Thank you...

**Comment by thisroot** [comment]
> Can you share a full code example I can test with? It should be working, and I can't tell what's wrong from those snippets. Thanks!

Later bro... thanks!

**Comment by jmeistrich** [comment]
beta.26 has logging to warn if the `name` parameter is not included. Thanks!
